### ISSUE TITLE
Typo ex 97

### ISSUE THREAD

**Issue by Nifrec** [benediktahrens/CT4P#26]
I think there is a typing mistake in exercise 97.
It says *"there is a morphism* $f \in \mathcal{C}_0$ *such that the following
diagram commutes..."*.
I think it should be $f \in \mathsf{hom}(P, Q)$ instead?

**Comment by benediktahrens** [comment]
Yes, you are right, that's a typo. Thanks for reporting!

Would you be interested in filing a PR? In this way, the commit history records your contribution.
